const I18N={
ps:{ageTitle:"یوازې د ۱۸ کلونو پورته",ageText:"دا ویب‌سایټ د بالغانو محتوا لري. د ننوتلو لپاره باید ۱۸ کلن یا تر هغه پورته یاست.",enter18:"زه ۱۸ کلن یا تر هغه پورته یم",leave:"وتل",ageNote:"د ازمایښت Age Gate. د اصلي سایټ لپاره قانوني age-assurance خدمت ونښلوئ.",adultOnly:"یوازې ۱۸+",consent:"یوازې قانوني او د رضایت وړ بالغ محتوا",home:"کور",videos:"ویډیوګانې",membership:"غړیتوب",payment:"تادیه",login:"ننوتل",heroTitle:"د بالغانو Premium ویډیوګانې.<br><em>خصوصي. ښکلې. ساده.</em>",heroText:"د بالغو ویډیوګانو منظم تجربه، وړیا ویډیوګانې او Premium غړیتوب په یوه پاک او خوندي انټرېفېس کې.",explore:"ویډیوګانې وګورئ",viewPlans:"غړیتوب وګورئ",featured:"ځانګړې مجموعه",premiumCollection:"Premium Collection",membersOnly:"یوازې غړو ته",adult:"د بالغانو لپاره",quality:"لوړ کیفیت",access:"د غړو لاسرسی",languages:"ژبې",library:"ویډیو کتابتون",latest:"نوې ویډیوګانې",libraryText:"Free ویډیوګانې د ټولو لپاره دي؛ Premium ویډیوګانې فعال غړیتوب غواړي.",all:"ټولې",free:"وړیا",premium:"Premium",loading:"ویډیوګانې بارېږي…",unlock:"ټول کتابتون خلاص کړئ",plansText:"پلان انتخاب کړئ، تادیه واستوئ او د Admin تایید ته انتظار وکړئ.",monthlyTag:"۳۰ ورځې",quarterTag:"۹۰ ورځې",monthly:"میاشتنی",quarterly:"درې میاشتنی",monthDesc:"د ۳۰ ورځو بشپړ Premium لاسرسی.",quarterDesc:"د ۹۰ ورځو بشپړ Premium لاسرسی.",choose:"پلان انتخاب",popular:"ډېر غوره",payTitle:"اسانه USDT تادیه",payText:"د پلان دقیق مبلغ واستوئ، بیا Transaction ID ثبت کړئ.",binanceId:"Binance ID",trcAddress:"TRC20 Address",copy:"کاپي",activate:"فعالول",submitTitle:"خپله تادیه ثبت کړئ",submitText:"لومړی Login وکړئ، پلان انتخاب کړئ او Contact او Transaction ID ولیکئ.",noPlan:"هیڅ پلان نه دی انتخاب شوی",submit:"تادیه واستوئ",safety:"خوندیتوب او رضایت",safetyTitle:"یوازې بالغ، رضاکارانه او قانوني محتوا",safetyText:"اپلوډ کوونکي باید د خپرولو حق او اړین رضایت ولري. د کم عمره کسانو، بې رضایته شخصي محتوا او غیرقانوني موادو اجازه نشته.",footer:"د ۱۸+ بالغو ویډیوګانو غړیتوب پلیټفارم."},
ar:{ageTitle:"للبالغين 18+",ageText:"يحتوي هذا الموقع على محتوى للبالغين. يجب أن يكون عمرك 18 عاماً أو أكثر للدخول.",enter18:"أنا 18 عاماً أو أكثر",leave:"مغادرة",ageNote:"بوابة عمر تجريبية. استخدم خدمة تحقق عمر متوافقة قانونياً عند الإطلاق.",adultOnly:"للبالغين 18+",consent:"محتوى قانوني وبرضا جميع البالغين",home:"الرئيسية",videos:"الفيديوهات",membership:"العضوية",payment:"الدفع",login:"تسجيل الدخول",heroTitle:"فيديوهات للبالغين.<br><em>خاصة. أنيقة. بسيطة.</em>",heroText:"تجربة فيديو للبالغين مع محتوى مجاني وعضوية Premium وواجهة خاصة ونظيفة.",explore:"استكشف الفيديوهات",viewPlans:"عرض العضوية",featured:"مجموعة مميزة",premiumCollection:"المجموعة المميزة",membersOnly:"للأعضاء فقط",adult:"للبالغين",quality:"جودة عالية",access:"وصول الأعضاء",languages:"لغات",library:"مكتبة الفيديو",latest:"أحدث الفيديوهات",libraryText:"الفيديوهات المجانية للجميع؛ فيديوهات Premium تتطلب عضوية فعالة.",all:"الكل",free:"مجاني",premium:"Premium",loading:"جاري تحميل الفيديوهات…",unlock:"افتح المكتبة كاملة",plansText:"اختر خطة وأرسل الدفع وانتظر تأكيد الإدارة.",monthlyTag:"30 يوماً",quarterTag:"90 يوماً",monthly:"شهري",quarterly:"ربع سنوي",monthDesc:"وصول Premium كامل لمدة 30 يوماً.",quarterDesc:"وصول Premium كامل لمدة 90 يوماً.",choose:"اختيار الخطة",popular:"الأكثر شعبية",payTitle:"دفع USDT بسيط",payText:"أرسل المبلغ الصحيح ثم أرسل Transaction ID.",binanceId:"معرف Binance",trcAddress:"عنوان TRC20",copy:"نسخ",activate:"تفعيل",submitTitle:"إرسال الدفع",submitText:"سجّل الدخول واختر الخطة ثم أدخل بيانات الاتصال وTransaction ID.",noPlan:"لم يتم اختيار خطة",submit:"إرسال الدفع",safety:"الأمان والموافقة",safetyTitle:"محتوى للبالغين قانوني وبرضاهم فقط",safetyText:"يجب أن يملك الرافع حقوق النشر والموافقات اللازمة. يمنع محتوى القاصرين أو المحتوى الحميمي غير الرضائي أو غير القانوني.",footer:"منصة عضوية لفيديوهات البالغين 18+."},
en:{ageTitle:"Adults only",ageText:"This website contains adult content. You must be 18 or older to enter.",enter18:"I am 18 or older",leave:"Leave site",ageNote:"Demo age gate. For production, connect a legally compliant age-assurance provider.",adultOnly:"18+ Adults Only",consent:"Only lawful, consensual adult content",home:"Home",videos:"Videos",membership:"Membership",payment:"Payment",login:"Login",heroTitle:"Premium adult video.<br><em>Private. Elegant. Simple.</em>",heroText:"Discover a curated adult video experience with free videos, premium access and a clean private interface.",explore:"Explore videos",viewPlans:"View membership",featured:"Featured collection",premiumCollection:"Premium Collection",membersOnly:"Members only",adult:"Adults only",quality:"High quality",access:"Member access",languages:"Languages",library:"VIDEO LIBRARY",latest:"Latest videos",libraryText:"Free videos are open to everyone. Premium videos require an active membership.",all:"All",free:"Free",premium:"Premium",loading:"Loading videos…",unlock:"Unlock the full library",plansText:"Choose a plan, send payment and wait for admin confirmation.",monthlyTag:"30 DAYS",quarterTag:"90 DAYS",monthly:"Monthly",quarterly:"Quarterly",monthDesc:"Full premium access for 30 days.",quarterDesc:"Full premium access for 90 days.",choose:"Choose plan",popular:"POPULAR",payTitle:"Simple USDT payment",payText:"Send the exact plan amount, then submit your transaction ID.",binanceId:"Binance ID",trcAddress:"TRC20 address",copy:"Copy",activate:"ACTIVATE",submitTitle:"Submit your payment",submitText:"Login first, select a plan, then enter your contact and transaction ID.",noPlan:"No plan selected",submit:"Submit payment",safety:"SAFETY & CONSENT",safetyTitle:"Adults, consent and lawful content only",safetyText:"Uploaders must have the rights and consent required to publish content. No minors, non-consensual intimate content, or illegal material.",footer:"18+ adult video membership platform."},
tr:{ageTitle:"Yalnızca 18+",ageText:"Bu site yetişkin içeriği içerir. Girmek için 18 yaşında veya daha büyük olmalısınız.",enter18:"18 yaşındayım veya daha büyüğüm",leave:"Ayrıl",ageNote:"Demo yaş kapısı. Yayında yasalara uygun bir yaş doğrulama hizmeti bağlayın.",adultOnly:"18+ Yetişkinler",consent:"Yalnızca yasal ve rızaya dayalı yetişkin içeriği",home:"Ana Sayfa",videos:"Videolar",membership:"Üyelik",payment:"Ödeme",login:"Giriş",heroTitle:"Premium yetişkin videoları.<br><em>Özel. Zarif. Basit.</em>",heroText:"Ücretsiz videolar, Premium erişim ve temiz özel arayüzle yetişkin video deneyimini keşfedin.",explore:"Videoları keşfet",viewPlans:"Üyeliği görüntüle",featured:"Öne çıkan koleksiyon",premiumCollection:"Premium Koleksiyon",membersOnly:"Sadece üyeler",adult:"Yetişkinler",quality:"Yüksek kalite",access:"Üye erişimi",languages:"Diller",library:"VİDEO KÜTÜPHANESİ",latest:"Son videolar",libraryText:"Ücretsiz videolar herkese açıktır. Premium videolar aktif üyelik gerektirir.",all:"Tümü",free:"Ücretsiz",premium:"Premium",loading:"Videolar yükleniyor…",unlock:"Tüm kütüphaneyi aç",plansText:"Plan seçin, ödeme gönderin ve yönetici onayını bekleyin.",monthlyTag:"30 GÜN",quarterTag:"90 GÜN",monthly:"Aylık",quarterly:"3 Aylık",monthDesc:"30 gün tam Premium erişim.",quarterDesc:"90 gün tam Premium erişim.",choose:"Planı seç",popular:"POPÜLER",payTitle:"Kolay USDT ödemesi",payText:"Plan tutarını gönderin ve Transaction ID bilgisini iletin.",binanceId:"Binance ID",trcAddress:"TRC20 adresi",copy:"Kopyala",activate:"AKTİFLEŞTİR",submitTitle:"Ödemenizi gönderin",submitText:"Önce giriş yapın, planı seçin, iletişim ve Transaction ID bilgilerini girin.",noPlan:"Plan seçilmedi",submit:"Ödemeyi gönder",safety:"GÜVENLİK VE RIZA",safetyTitle:"Yalnızca yetişkin, rızaya dayalı ve yasal içerik",safetyText:"Yükleyenler gerekli haklara ve rızalara sahip olmalıdır. Reşit olmayanlar, rıza dışı mahrem içerik ve yasa dışı materyal yasaktır.",footer:"18+ yetişkin video üyelik platformu."},
ru:{ageTitle:"Только 18+",ageText:"На сайте есть контент для взрослых. Для входа вам должно быть 18 лет или больше.",enter18:"Мне 18 лет или больше",leave:"Выйти",ageNote:"Демо-проверка возраста. Для запуска подключите юридически соответствующий сервис.",adultOnly:"Только 18+",consent:"Только законный контент взрослых по взаимному согласию",home:"Главная",videos:"Видео",membership:"Подписка",payment:"Оплата",login:"Войти",heroTitle:"Премиум-видео для взрослых.<br><em>Приватно. Элегантно. Просто.</em>",heroText:"Каталог видео для взрослых с бесплатными роликами, Premium-доступом и чистым приватным интерфейсом.",explore:"Смотреть видео",viewPlans:"Посмотреть подписку",featured:"Избранная коллекция",premiumCollection:"Premium коллекция",membersOnly:"Только для участников",adult:"Только взрослые",quality:"Высокое качество",access:"Доступ участникам",languages:"Языков",library:"ВИДЕОТЕКА",latest:"Новые видео",libraryText:"Бесплатные видео доступны всем. Premium-видео требуют активной подписки.",all:"Все",free:"Бесплатно",premium:"Premium",loading:"Загрузка видео…",unlock:"Открыть всю библиотеку",plansText:"Выберите план, отправьте оплату и дождитесь подтверждения администратора.",monthlyTag:"30 ДНЕЙ",quarterTag:"90 ДНЕЙ",monthly:"Месячный",quarterly:"Квартальный",monthDesc:"Полный Premium-доступ на 30 дней.",quarterDesc:"Полный Premium-доступ на 90 дней.",choose:"Выбрать план",popular:"ПОПУЛЯРНО",payTitle:"Простая оплата USDT",payText:"Отправьте точную сумму и затем укажите Transaction ID.",binanceId:"Binance ID",trcAddress:"Адрес TRC20",copy:"Копировать",activate:"АКТИВАЦИЯ",submitTitle:"Отправить оплату",submitText:"Войдите, выберите план и укажите контакт и Transaction ID.",noPlan:"План не выбран",submit:"Отправить оплату",safety:"БЕЗОПАСНОСТЬ И СОГЛАСИЕ",safetyTitle:"Только законный контент взрослых с согласием",safetyText:"Загрузчики должны иметь права и необходимые согласия. Запрещены несовершеннолетние, интимный контент без согласия и незаконные материалы.",footer:"Платформа подписки на видео для взрослых 18+."}
};
let lang=localStorage.getItem("sv_lang")||"en",authMode="login",selectedPlan=null,currentFilter="all";
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function setLang(l){lang=l;localStorage.setItem("sv_lang",l);const d=I18N[l]||I18N.en;document.documentElement.lang=l;document.documentElement.dir=(l==="ps"||l==="ar")?"rtl":"ltr";$$("[data-i18n]").forEach(e=>e.innerHTML=d[e.dataset.i18n]??e.innerHTML);$$("[data-ph]").forEach(e=>e.placeholder={name:{ps:"نوم",ar:"الاسم",en:"Name",tr:"Ad",ru:"Имя"},email:{ps:"ایمیل",ar:"البريد الإلكتروني",en:"Email",tr:"E-posta",ru:"Email"},password:{ps:"پټ نوم (لږ تر لږه ۸ کرکټر)",ar:"كلمة المرور (8 أحرف+)",en:"Password (8+ characters)",tr:"Şifre (8+ karakter)",ru:"Пароль (8+ символов)"},contact:{ps:"Telegram یا Email",ar:"Telegram أو البريد",en:"Telegram or email",tr:"Telegram veya e-posta",ru:"Telegram или email"},txid:{ps:"Transaction ID / Hash",ar:"رقم المعاملة / Hash",en:"Transaction ID / hash",tr:"Transaction ID / hash",ru:"Transaction ID / hash"} }[e.dataset.ph]?.[l]||e.placeholder);$("#lang").value=l;loadVideos();}
$("#lang").onchange=e=>setLang(e.target.value);
$("#enterBtn").onclick=()=>{localStorage.setItem("sv_age_ok","1");$("#ageGate").classList.add("hidden")};
$("#leaveBtn").onclick=()=>location.href="https://www.google.com";
if(localStorage.getItem("sv_age_ok")==="1")$("#ageGate").classList.add("hidden");
async function api(u,o={}){const r=await fetch(u,o);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
async function loadConfig(){const c=await api("/api/config");$("#binance").textContent=c.binanceId;$("#trc").textContent=c.usdtAddress}
function renderVideos(vs){const d=I18N[lang]||I18N.en;const list=vs.filter(v=>currentFilter==="all"||v.access===currentFilter);$("#videoGrid").innerHTML=list.length?list.map(v=>`<article class="video-card"><div class="thumb"><span class="badge ${v.access}">${v.access==="free"?d.free:d.premium}</span><div class="play">▶</div></div><div class="card-body"><h3>${esc(v.title)}</h3><p>${esc(v.description||"Premium adult video")}</p><div class="card-foot"><span>${v.access==="paid"&&v.price?`$${v.price}`:"FREE"}</span><button class="watch" onclick="watchVideo(${v.id},'${v.access}')">${v.access==="paid"?"🔒 ":""}${d.explore}</button></div></div></article>`).join(""):`<div class="empty">${d.loading}</div>`}
async function loadVideos(){try{const d=await api("/api/videos");renderVideos(d.videos)}catch(e){$("#videoGrid").innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}
async function watchVideo(id,access){if(access==="paid"){try{await api("/api/me")}catch{$("#loginBtn").click();return}}const p=$("#player");p.src="/api/videos/"+id;$("#videoModal").classList.add("show");p.play().catch(()=>{})}
function closeVideo(){const p=$("#player");p.pause();p.removeAttribute("src");$("#videoModal").classList.remove("show")}
function openAuth(){ $("#authModal").classList.add("show");$("#authTitle").textContent=I18N[lang][authMode==="login"?"login":"createAccount"]|| (authMode==="login"?"Login":"Create account");$("#authName").style.display=authMode==="login"?"none":"block"}
$("#loginBtn").onclick=openAuth;$("#closeAuth").onclick=()=>$("#authModal").classList.remove("show");$("#closeVideo").onclick=closeVideo;
$("#toggleAuth").onclick=()=>{authMode=authMode==="login"?"register":"login";$("#toggleAuth").textContent=authMode==="login"?"Create an account":"Already have an account";openAuth()};
$("#authSubmit").onclick=async()=>{try{const body={email:$("#authEmail").value,password:$("#authPassword").value};if(authMode==="register")body.name=$("#authName").value;const d=await api("/api/"+authMode,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});$("#authModal").classList.remove("show");$("#loginBtn").textContent=d.user.name;$("#authNotice").textContent=""}catch(e){$("#authNotice").textContent=e.message}};
$$(".choose").forEach(b=>b.onclick=()=>{selectedPlan={plan:b.dataset.plan,price:b.dataset.price};$("#selectedPlan").textContent=`${b.dataset.plan==="monthly"?I18N[lang].monthly:I18N[lang].quarterly} — $${b.dataset.price} USDT`;location.hash="payment"});
$("#submitPayment").onclick=async()=>{try{if(!selectedPlan){$("#notice").textContent=I18N[lang].noPlan;return}const d=await api("/api/payments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({plan:selectedPlan.plan,txid:$("#txid").value,contact:$("#contact").value})});$("#notice").textContent="✓ "+(d.message||"Submitted");}catch(e){if(e.message==="Login required.")openAuth();else $("#notice").textContent=e.message}};
$$(".copy").forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText($("#"+b.dataset.copy).textContent);b.textContent="✓";setTimeout(()=>b.textContent=I18N[lang].copy,900)});
$$(".filter").forEach(b=>b.onclick=()=>{$$(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");currentFilter=b.dataset.filter;loadVideos()});
$("#menuBtn").onclick=()=>$("#nav").classList.toggle("open");
loadConfig();setLang(lang);
